org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-rftoolsbuilder
addon_name=BlueMap RFTools Builder Add-on
addon_version=0.1.0-alpha.2
addon_group=io.github.jan-guenter
artifact_id=bluemap-rftools-builder-addon
bluemap_version=5.22-feature.backport-5.23-stateless-java-web-server-46
accepted_jar_size=70037
accepted_jar_sha256=3302fbf77a92cc0643e04dfe7981816a3699b0da00f3993360b6b76ca389c09b
accepted_sources_jar_size=51407
accepted_sources_jar_sha256=a75842ab39d32a08fc1df5631c1406c12add8613621f7777c6161b117baede2d
accepted_pom_size=1378
accepted_pom_sha256=c29f9ccf30dbc1e22c84524d1d75eb42120a4255009bedbd7b41e76147af0011
accepted_module_size=2873
accepted_module_sha256=c580a12773d0aafd87dfb97763e0314ef3e2a3dee1f29f770c82d4443b3235b6
