org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-rftoolsbuilder
addon_name=BlueMap RFTools Builder Add-on
addon_version=0.1.0-alpha.1
addon_group=io.github.jan-guenter
artifact_id=bluemap-rftools-builder-addon
bluemap_version=5.22-agent.backport-5.22-mc1.21.1-2
accepted_jar_size=65006
accepted_jar_sha256=776d4242bf6826a8aafe081aca5b32f242bc0af5677efccbdd3469b65ba7cfe6
accepted_sources_jar_size=46071
accepted_sources_jar_sha256=151d339992c7a79cdc7098e28a1bc687d4d591bcec7234ce130ed448f67c2dc9
accepted_pom_size=1378
accepted_pom_sha256=474907777785ec36ab0fecc385ac96b7941d2dd36864cf7d6c236b985956901d
accepted_module_size=2873
accepted_module_sha256=93b7081cb7f1ef6e38c7a589daa496147046110c83315030896c83163cc1ea19
