# Generated by gallery/generate.py; do not edit.
scoreboard objectives add rftb_gallery dummy
scoreboard players add #builds rftb_gallery 1
function rftools_builder_gallery:clear
forceload add 160 160 183 183
fill 160 99 160 180 99 181 minecraft:smooth_stone
# A: stock projector and default render-data source
setblock 164 100 164 rftoolsbuilder:shield_block1
# A: stock blue shield template
setblock 168 100 164 rftoolsbuilder:blue_shield_template_block
# A: stock bricks
setblock 172 100 164 minecraft:bricks
# B: isolated shield default mint
setblock 164 100 171 rftoolsbuilder:shielding_translucent[bh=false,bi=false,bp=false,bplay=false,dh=false,di=false,dp=false,dplay=false,opaque=true,render=shield]{sx:164,sy:100,sz:164}
# B: isolated transparent default mint
setblock 168 100 171 rftoolsbuilder:shielding_translucent[bh=false,bi=false,bp=false,bplay=false,dh=false,di=false,dp=false,dplay=false,opaque=true,render=transp]{sx:164,sy:100,sz:164}
# B: isolated solid default mint
setblock 172 100 171 rftoolsbuilder:shielding_solid[bh=false,bi=false,bp=false,bplay=false,dh=false,di=false,dp=false,dplay=false,opaque=true,render=solid]{sx:164,sy:100,sz:164}
# B: invisible zero-geometry control
setblock 176 100 171 rftoolsbuilder:shielding_translucent[bh=false,bi=false,bp=false,bplay=false,dh=false,di=false,dp=false,dplay=false,opaque=true,render=invisible]{sx:164,sy:100,sz:164}
# C: shield cluster top parity 0 north-west
setblock 164 100 178 rftoolsbuilder:shielding_translucent[bh=false,bi=false,bp=false,bplay=false,dh=false,di=false,dp=false,dplay=false,opaque=true,render=shield]{sx:164,sy:100,sz:164}
# C: shield cluster top parity 1 north-east
setblock 165 100 178 rftoolsbuilder:shielding_translucent[bh=false,bi=false,bp=false,bplay=false,dh=false,di=false,dp=false,dplay=false,opaque=true,render=shield]{sx:164,sy:100,sz:164}
# C: shield cluster top parity 2 south-west
setblock 164 100 179 rftoolsbuilder:shielding_translucent[bh=false,bi=false,bp=false,bplay=false,dh=false,di=false,dp=false,dplay=false,opaque=true,render=shield]{sx:164,sy:100,sz:164}
# C: shield cluster top parity 3 south-east
setblock 165 100 179 rftoolsbuilder:shielding_translucent[bh=false,bi=false,bp=false,bplay=false,dh=false,di=false,dp=false,dplay=false,opaque=true,render=shield]{sx:164,sy:100,sz:164}
function rftools_builder_gallery:verify_immediate
schedule function rftools_builder_gallery:verify_20t 20t replace
