# Generated by gallery/generate.py; do not edit.
function rftools_builder_gallery:verify
scoreboard players operation #immediate_failures rftb_gallery = #failures rftb_gallery
scoreboard players operation #immediate_checked rftb_gallery = #checked rftb_gallery
tellraw @a [{"text":"RFToolsBuilder gallery immediate: "},{"score":{"name":"#immediate_checked","objective":"rftb_gallery"}},{"text":" checks, "},{"score":{"name":"#immediate_failures","objective":"rftb_gallery"}},{"text":" failures"}]
