# Generated by gallery/generate.py; do not edit.
scoreboard players set #failures rftb_gallery 0
scoreboard players set #checked rftb_gallery 0
# A: stock projector and default render-data source
execute unless block 164 100 164 rftoolsbuilder:shield_block1 run scoreboard players add #failures rftb_gallery 1
scoreboard players add #checked rftb_gallery 1
# A: stock blue shield template
execute unless block 168 100 164 rftoolsbuilder:blue_shield_template_block run scoreboard players add #failures rftb_gallery 1
scoreboard players add #checked rftb_gallery 1
# A: stock bricks
execute unless block 172 100 164 minecraft:bricks run scoreboard players add #failures rftb_gallery 1
scoreboard players add #checked rftb_gallery 1
# B: isolated shield default mint
execute unless block 164 100 171 rftoolsbuilder:shielding_translucent[bh=false,bi=false,bp=false,bplay=false,dh=false,di=false,dp=false,dplay=false,opaque=true,render=shield] run scoreboard players add #failures rftb_gallery 1
scoreboard players add #checked rftb_gallery 1
execute unless data block 164 100 171 {sx:164,sy:100,sz:164} run scoreboard players add #failures rftb_gallery 1
scoreboard players add #checked rftb_gallery 1
# B: isolated transparent default mint
execute unless block 168 100 171 rftoolsbuilder:shielding_translucent[bh=false,bi=false,bp=false,bplay=false,dh=false,di=false,dp=false,dplay=false,opaque=true,render=transp] run scoreboard players add #failures rftb_gallery 1
scoreboard players add #checked rftb_gallery 1
execute unless data block 168 100 171 {sx:164,sy:100,sz:164} run scoreboard players add #failures rftb_gallery 1
scoreboard players add #checked rftb_gallery 1
# B: isolated solid default mint
execute unless block 172 100 171 rftoolsbuilder:shielding_solid[bh=false,bi=false,bp=false,bplay=false,dh=false,di=false,dp=false,dplay=false,opaque=true,render=solid] run scoreboard players add #failures rftb_gallery 1
scoreboard players add #checked rftb_gallery 1
execute unless data block 172 100 171 {sx:164,sy:100,sz:164} run scoreboard players add #failures rftb_gallery 1
scoreboard players add #checked rftb_gallery 1
# B: invisible zero-geometry control
execute unless block 176 100 171 rftoolsbuilder:shielding_translucent[bh=false,bi=false,bp=false,bplay=false,dh=false,di=false,dp=false,dplay=false,opaque=true,render=invisible] run scoreboard players add #failures rftb_gallery 1
scoreboard players add #checked rftb_gallery 1
execute unless data block 176 100 171 {sx:164,sy:100,sz:164} run scoreboard players add #failures rftb_gallery 1
scoreboard players add #checked rftb_gallery 1
# C: shield cluster top parity 0 north-west
execute unless block 164 100 178 rftoolsbuilder:shielding_translucent[bh=false,bi=false,bp=false,bplay=false,dh=false,di=false,dp=false,dplay=false,opaque=true,render=shield] run scoreboard players add #failures rftb_gallery 1
scoreboard players add #checked rftb_gallery 1
execute unless data block 164 100 178 {sx:164,sy:100,sz:164} run scoreboard players add #failures rftb_gallery 1
scoreboard players add #checked rftb_gallery 1
# C: shield cluster top parity 1 north-east
execute unless block 165 100 178 rftoolsbuilder:shielding_translucent[bh=false,bi=false,bp=false,bplay=false,dh=false,di=false,dp=false,dplay=false,opaque=true,render=shield] run scoreboard players add #failures rftb_gallery 1
scoreboard players add #checked rftb_gallery 1
execute unless data block 165 100 178 {sx:164,sy:100,sz:164} run scoreboard players add #failures rftb_gallery 1
scoreboard players add #checked rftb_gallery 1
# C: shield cluster top parity 2 south-west
execute unless block 164 100 179 rftoolsbuilder:shielding_translucent[bh=false,bi=false,bp=false,bplay=false,dh=false,di=false,dp=false,dplay=false,opaque=true,render=shield] run scoreboard players add #failures rftb_gallery 1
scoreboard players add #checked rftb_gallery 1
execute unless data block 164 100 179 {sx:164,sy:100,sz:164} run scoreboard players add #failures rftb_gallery 1
scoreboard players add #checked rftb_gallery 1
# C: shield cluster top parity 3 south-east
execute unless block 165 100 179 rftoolsbuilder:shielding_translucent[bh=false,bi=false,bp=false,bplay=false,dh=false,di=false,dp=false,dplay=false,opaque=true,render=shield] run scoreboard players add #failures rftb_gallery 1
scoreboard players add #checked rftb_gallery 1
execute unless data block 165 100 179 {sx:164,sy:100,sz:164} run scoreboard players add #failures rftb_gallery 1
scoreboard players add #checked rftb_gallery 1
execute unless score #builds rftb_gallery matches 1 run scoreboard players add #failures rftb_gallery 1
scoreboard players add #checked rftb_gallery 1
