# Generated by gallery/generate.py; do not edit.
function rftools_builder_gallery:verify
scoreboard players operation #20t_failures rftb_gallery = #failures rftb_gallery
scoreboard players operation #20t_checked rftb_gallery = #checked rftb_gallery
tellraw @a [{"text":"RFToolsBuilder gallery 20t: "},{"score":{"name":"#20t_checked","objective":"rftb_gallery"}},{"text":" checks, "},{"score":{"name":"#20t_failures","objective":"rftb_gallery"}},{"text":" failures"}]
