#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate the bounded RFToolsBuilder staging gallery."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import hashlib
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parent
NAMESPACE = "rftools_builder_gallery"
OBJECTIVE = "rftb_gallery"
ENVELOPE = {
    "min_x": 160,
    "max_x": 183,
    "min_y": 99,
    "max_y": 104,
    "min_z": 160,
    "max_z": 183,
}
PAD = (160, 99, 160, 180, 99, 181)
PROJECTOR = (164, 100, 164)
PROJECTOR_NBT = "{sx:164,sy:100,sz:164}"


def shielding_state(block_id: str, render: str) -> str:
    return (
        f"{block_id}[bh=false,bi=false,bp=false,bplay=false,"
        "dh=false,di=false,dp=false,dplay=false,opaque=true,"
        f"render={render}]"
    )


SHIELD = shielding_state("rftoolsbuilder:shielding_translucent", "shield")
TRANSP = shielding_state("rftoolsbuilder:shielding_translucent", "transp")
SOLID = shielding_state("rftoolsbuilder:shielding_solid", "solid")
INVISIBLE = shielding_state(
    "rftoolsbuilder:shielding_translucent", "invisible"
)


@dataclass(frozen=True)
class Placement:
    section: str
    label: str
    x: int
    y: int
    z: int
    block_state: str
    nbt: str | None
    expected: str


PLACEMENTS = (
    Placement(
        "A",
        "stock projector and default render-data source",
        164,
        100,
        164,
        "rftoolsbuilder:shield_block1",
        None,
        "stock-control",
    ),
    Placement(
        "A",
        "stock blue shield template",
        168,
        100,
        164,
        "rftoolsbuilder:blue_shield_template_block",
        None,
        "stock-control",
    ),
    Placement(
        "A",
        "stock bricks",
        172,
        100,
        164,
        "minecraft:bricks",
        None,
        "stock-control",
    ),
    Placement(
        "B",
        "isolated shield default mint",
        164,
        100,
        171,
        SHIELD,
        PROJECTOR_NBT,
        "custom-visible",
    ),
    Placement(
        "B",
        "isolated transparent default mint",
        168,
        100,
        171,
        TRANSP,
        PROJECTOR_NBT,
        "custom-visible",
    ),
    Placement(
        "B",
        "isolated solid default mint",
        172,
        100,
        171,
        SOLID,
        PROJECTOR_NBT,
        "custom-visible",
    ),
    Placement(
        "B",
        "invisible zero-geometry control",
        176,
        100,
        171,
        INVISIBLE,
        PROJECTOR_NBT,
        "custom-zero",
    ),
    Placement(
        "C",
        "shield cluster top parity 0 north-west",
        164,
        100,
        178,
        SHIELD,
        PROJECTOR_NBT,
        "custom-visible",
    ),
    Placement(
        "C",
        "shield cluster top parity 1 north-east",
        165,
        100,
        178,
        SHIELD,
        PROJECTOR_NBT,
        "custom-visible",
    ),
    Placement(
        "C",
        "shield cluster top parity 2 south-west",
        164,
        100,
        179,
        SHIELD,
        PROJECTOR_NBT,
        "custom-visible",
    ),
    Placement(
        "C",
        "shield cluster top parity 3 south-east",
        165,
        100,
        179,
        SHIELD,
        PROJECTOR_NBT,
        "custom-visible",
    ),
)


def text_bytes(text: str) -> bytes:
    return (text.rstrip() + "\n").encode("utf-8")


def json_bytes(value: object) -> bytes:
    return (json.dumps(value, indent=2, sort_keys=True) + "\n").encode(
        "utf-8"
    )


def placements_tsv() -> bytes:
    lines = [
        "section\tlabel\tx\ty\tz\tblock_state\tblock_entity_nbt\texpected"
    ]
    lines.extend(
        "\t".join(
            (
                placement.section,
                placement.label,
                str(placement.x),
                str(placement.y),
                str(placement.z),
                placement.block_state,
                placement.nbt or "-",
                placement.expected,
            )
        )
        for placement in PLACEMENTS
    )
    return text_bytes("\n".join(lines))


def build_function() -> bytes:
    lines = [
        "# Generated by gallery/generate.py; do not edit.",
        f"scoreboard objectives add {OBJECTIVE} dummy",
        f"scoreboard players add #builds {OBJECTIVE} 1",
        f"function {NAMESPACE}:clear",
        "forceload add 160 160 183 183",
        "fill 160 99 160 180 99 181 minecraft:smooth_stone",
    ]
    for placement in PLACEMENTS:
        lines.append(f"# {placement.section}: {placement.label}")
        suffix = placement.nbt or ""
        lines.append(
            f"setblock {placement.x} {placement.y} {placement.z} "
            f"{placement.block_state}{suffix}"
        )
    lines.extend(
        (
            f"function {NAMESPACE}:verify_immediate",
            f"schedule function {NAMESPACE}:verify_20t 20t replace",
        )
    )
    return text_bytes("\n".join(lines))


def failure_check(condition: str) -> str:
    return (
        f"execute unless {condition} run scoreboard players add "
        f"#failures {OBJECTIVE} 1"
    )


def verify_function() -> bytes:
    lines = [
        "# Generated by gallery/generate.py; do not edit.",
        f"scoreboard players set #failures {OBJECTIVE} 0",
        f"scoreboard players set #checked {OBJECTIVE} 0",
    ]
    for placement in PLACEMENTS:
        lines.append(f"# {placement.section}: {placement.label}")
        lines.append(
            failure_check(
                f"block {placement.x} {placement.y} {placement.z} "
                f"{placement.block_state}"
            )
        )
        lines.append(f"scoreboard players add #checked {OBJECTIVE} 1")
        if placement.nbt is not None:
            lines.append(
                failure_check(
                    f"data block {placement.x} {placement.y} {placement.z} "
                    f"{placement.nbt}"
                )
            )
            lines.append(f"scoreboard players add #checked {OBJECTIVE} 1")
    lines.extend(
        (
            f"execute unless score #builds {OBJECTIVE} matches 1 run "
            f"scoreboard players add #failures {OBJECTIVE} 1",
            f"scoreboard players add #checked {OBJECTIVE} 1",
        )
    )
    return text_bytes("\n".join(lines))


def phase_function(phase: str, announce: bool) -> bytes:
    lines = [
        "# Generated by gallery/generate.py; do not edit.",
        f"function {NAMESPACE}:verify",
        f"scoreboard players operation #{phase}_failures {OBJECTIVE} = "
        f"#failures {OBJECTIVE}",
        f"scoreboard players operation #{phase}_checked {OBJECTIVE} = "
        f"#checked {OBJECTIVE}",
    ]
    if announce:
        payload = [
            {"text": f"RFToolsBuilder gallery {phase}: "},
            {"score": {"name": f"#{phase}_checked", "objective": OBJECTIVE}},
            {"text": " checks, "},
            {
                "score": {
                    "name": f"#{phase}_failures",
                    "objective": OBJECTIVE,
                }
            },
            {"text": " failures"},
        ]
        lines.append("tellraw @a " + json.dumps(payload, separators=(",", ":")))
    return text_bytes("\n".join(lines))


def base_files() -> dict[Path, bytes]:
    function_root = Path(f"datapack/data/{NAMESPACE}/function")
    return {
        Path("placements.tsv"): placements_tsv(),
        Path("datapack/pack.mcmeta"): json_bytes(
            {
                "pack": {
                    "description": "ATM 1.2.0 RFToolsBuilder BlueMap gallery",
                    "pack_format": 48,
                }
            }
        ),
        Path("datapack/data/minecraft/tags/function/load.json"): json_bytes(
            {"values": [f"{NAMESPACE}:load"]}
        ),
        function_root / "load.mcfunction": text_bytes(
            "# Generated by gallery/generate.py; do not edit.\n"
            f"scoreboard objectives add {OBJECTIVE} dummy"
        ),
        function_root / "clear.mcfunction": text_bytes(
            "# Generated by gallery/generate.py; do not edit.\n"
            f"schedule clear {NAMESPACE}:verify_20t\n"
            "fill 160 99 160 183 104 183 minecraft:air"
        ),
        function_root / "build.mcfunction": build_function(),
        function_root / "verify.mcfunction": verify_function(),
        function_root / "verify_immediate.mcfunction": phase_function(
            "immediate", True
        ),
        function_root / "verify_20t.mcfunction": phase_function("20t", True),
        function_root / "release.mcfunction": text_bytes(
            "# Generated by gallery/generate.py; do not edit.\n"
            f"schedule clear {NAMESPACE}:verify_20t\n"
            "forceload remove 160 160 183 183"
        ),
    }


def sha256(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def generated_files() -> dict[Path, bytes]:
    files = base_files()
    checksum = "".join(
        f"{sha256(files[path])}  {path.as_posix()}\n"
        for path in sorted(files)
    )
    files[Path("SHA256SUMS")] = checksum.encode("ascii")
    return files


def write_or_check(check: bool) -> int:
    failures: list[str] = []
    files = generated_files()
    for relative, payload in files.items():
        path = ROOT / relative
        if check:
            if not path.is_file():
                failures.append(f"missing generated file: {relative}")
            elif path.read_bytes() != payload:
                failures.append(f"generated file differs: {relative}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(payload)
    if failures:
        print("\n".join(failures), file=sys.stderr)
        return 1
    action = "checked" if check else "wrote"
    print(f"{action} {len(files)} deterministic gallery files")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    return write_or_check(args.check)


if __name__ == "__main__":
    raise SystemExit(main())
